name: shindhu_study_companion
description: Offline-first AI study companion for SSC and competitive exam preparation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.0
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
